# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/workshop-kenya',
                'doc_host': 'https://kevinkorfmann.github.io',
                'git_url': 'https://github.com/kevinkorfmann/workshop-kenya',
                'lib_path': 'workshop_kenya'},
  'syms': { 'workshop_kenya.core': {'workshop_kenya.core.foo': ('core.html#foo', 'workshop_kenya/core.py')},
            'workshop_kenya.msms2haplo': {}}}
